definitions:
  content_service.Story:
    properties:
      author_id:
        type: string
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      location:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for API Gateway.
  title: API Gateway
  version: "1.0"
paths:
  /api/v1/stories:
    post:
      consumes:
      - application/json
      description: Post Story
      parameters:
      - description: Login Request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/content_service.Story'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/content_service.Story'
        "400":
          description: Error
          schema: {}
        "500":
          description: Error
          schema: {}
      summary: Post Story
      tags:
      - /api/v1
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
